#!/bin/bash


# get the directory of the current script
DIR="$( cd "$( dirname "$0" )" && pwd )"


# setup colors used for output
c_eol="\033[00m"
c_yel="\033[1;33m"
c_red="\033[1;31m"
c_grn="\033[1;32m"


# check to see if coffee-script is already installed
if [ -e `which coffee` ]
then
  echo -e "${c_grn}coffee-script is already installed${c_eol}"
  exit 0
fi


# check if node exists and only install if so
# if not, then install Node
if [ -e `which npm` ]
then
  echo -e "${c_yel}Installing coffee-script${c_eol}"
  npm install -g coffee-script &>/dev/null
  if [ $? -eq 0 ]
  then
    echo -e "${c_grn}coffee-script has successfully installed${c_eol}"
  else
    echo -e "${c_red}coffee-script could not be installed, try doing it manually... sorry${c_eol}"
  fi
else
  bash "${DIR}/npm"
  bash "${DIR}/coffee"
fi
