#!/bin/bash


# get the directory of the current script
DIR="$( cd "$( dirname "$0" )" && pwd )"


# setup colors used for output
c_eol="\033[00m"
c_yel="\033[1;33m"
c_red="\033[1;31m"
c_grn="\033[1;32m"


# check to see if it has already been installed
if [ -e `which npm` ]
then
  echo -e "${c_grn}NPM is already installed${c_eol}"
  exit 0
fi


# check if node exists and only install if so
# if not, then install Node
if [ -e `which node` ]
then
  curl http://npmjs.org/install.sh | sh
else
  bash "${DIR}/node"
  bash "${DIR}/npm"
fi
